"""
sim_incident_writer.py — Writes fixture bundle directory layout (US-1)

Given an exam question's evidence list, writes the sim-incident directory
structure that agents read in simulation mode.

Directory layout produced:
    .ops/exam-results/run-{ts}/sim-incidents/{qid}/
        _exam_mode_flag.yaml        # exact 5 required fields
        _dkr_access_log.yaml        # pre-written {violated: false} by preflight
        symptoms.md                 # human-readable scenario
        evidence/
            metrics.yaml            # evidence type=metric rows
            logs.yaml               # evidence type=log rows
            cli-outputs.yaml        # evidence type=cli_output | alarm | cloudtrail_event rows

Provenance footer added to every fixture YAML.

US-1 AC#1-8 compliance.
"""

from __future__ import annotations

import datetime
import textwrap
from pathlib import Path
from typing import Any

import yaml


HARNESS_VERSION = "aws-exam-harness/v1"

# Fixture types routed to cli-outputs.yaml
_CLI_OUTPUTS_TYPES = {"cli_output", "alarm", "cloudtrail_event"}


def _provenance_footer(question_id: str) -> dict[str, str]:
    """Return the provenance metadata appended to every fixture file. US-1 AC#7."""
    return {
        "generated_by": HARNESS_VERSION,
        "source_question": question_id,
        "generated_at": datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
    }


def write_exam_mode_flag(sim_dir: Path, question_id: str, created_at: str) -> None:
    """Write _exam_mode_flag.yaml with exactly the 5 required fields. US-1 AC#2."""
    flag = {
        "mode": "simulation",
        "question_id": question_id,
        "dkr_blind": True,
        "created_at": created_at,
        "agents_operating_mode": "simulation",
    }
    _write_yaml(sim_dir / "_exam_mode_flag.yaml", flag)


def write_symptoms(sim_dir: Path, question: dict[str, Any]) -> None:
    """Write symptoms.md from scenario context/situation/constraint. US-1 AC#1."""
    scenario = question.get("scenario", {})
    context = scenario.get("context", "")
    situation = scenario.get("situation", "")
    constraint = scenario.get("constraint", "")
    qid = question.get("id", "unknown")

    lines = [
        f"# Symptoms: {qid}",
        "",
        "## Context",
        textwrap.fill(context, width=100) if context else "_No context provided._",
        "",
        "## Situation",
        textwrap.fill(situation, width=100) if situation else "_No situation provided._",
        "",
    ]
    if constraint:
        lines += [
            "## Constraint",
            textwrap.fill(constraint, width=100),
            "",
        ]
    lines += [
        "---",
        f"_Generated by {HARNESS_VERSION} from exam question {qid}_",
    ]

    (sim_dir / "symptoms.md").write_text("\n".join(lines), encoding="utf-8")


def write_evidence_fixtures(
    evidence_dir: Path,
    evidence_list: list[dict[str, Any]],
    question_id: str,
) -> None:
    """Route evidence[] entries to the correct fixture file. US-1 AC#3-5."""
    metrics: dict[str, Any] = {}
    logs: list[dict[str, Any]] = []
    cli_outputs: list[dict[str, Any]] = []

    for entry in evidence_list:
        etype = entry.get("type", "")
        source = entry.get("source", "unknown_source")
        value = entry.get("value", "")

        if etype == "metric":
            # Keyed by source string per US-1 AC#3
            # Sanitize source to a YAML-safe key
            key = source.replace(" ", "_").replace("/", "_").replace(":", "").lower()
            metrics[key] = {
                "source": source,
                "value": value,
                "_original_type": "metric",
            }

        elif etype == "log":
            # US-1 AC#4: source, query_summary, sample_entries
            logs.append({
                "source": source,
                "query_summary": value,
                "sample_entries": [],  # populated by agent from query_summary context
                "_original_type": "log",
            })

        elif etype in _CLI_OUTPUTS_TYPES:
            # US-1 AC#5: command, mocked_output
            cli_outputs.append({
                "source": source,
                "command": _infer_command(etype, source, value),
                "mocked_output": value,
                "_original_type": etype,
            })

        else:
            # Unknown type — route to cli-outputs with passthrough
            cli_outputs.append({
                "source": source,
                "command": f"# unknown fixture type: {etype}",
                "mocked_output": value,
                "_original_type": etype,
            })

    prov = _provenance_footer(question_id)

    _write_yaml(
        evidence_dir / "metrics.yaml",
        {"metrics": metrics, "_provenance": prov} if metrics else {"metrics": {}, "_provenance": prov},
    )
    _write_yaml(
        evidence_dir / "logs.yaml",
        {"logs": logs, "_provenance": prov},
    )
    _write_yaml(
        evidence_dir / "cli-outputs.yaml",
        {"cli_outputs": cli_outputs, "_provenance": prov},
    )


def _infer_command(etype: str, source: str, value: str) -> str:
    """Best-effort inference of the AWS CLI command from fixture metadata.

    The authoritative mapping lives in exam-simulation-protocol.md (Task #5).
    This is a fallback placeholder so the fixture file is never empty.
    """
    if etype == "alarm":
        return f"aws cloudwatch describe-alarms --alarm-names \"{source}\""
    if etype == "cloudtrail_event":
        return f"aws cloudtrail lookup-events --lookup-attributes AttributeKey=EventName,AttributeValue=\"{source}\""
    # cli_output — source often contains the command name
    return f"# cli_output: {source}"


def _write_yaml(path: Path, data: Any) -> None:
    """Write data as YAML to path (UTF-8, unicode preserved)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        yaml.dump(data, fh, allow_unicode=True, default_flow_style=False, sort_keys=False)
